# The URL the site will be built for
base_url = "https://mfaishal.com/"

title = "Faishal Irawan - CS Student"
description = "CS Student from Indonesia."

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

taxonomies = [
    {name = "tags"},
]

[extra]
menus = ["article", "showcase", "about"]
blurb_title = "Hi, I'm Faishal Irawan"
blurb_desc = "CS student. Bandung, Indonesia. ようこそ."